const animal = {
	id: "",
	longitude: "",
	latitude: "",
	name: "",
	type: "",
	breed: "",
	info: "",
	imgPath: "",
};

export const animalData = [
	{
		id: 1,
		longitude: 21.01,
		latitude: 52.231,
		name: "Buddy",
		type: "Dog",
		breed: "Golden Retriever",
		info: "Friendly and playful",
		imgPath: "",
	},
	{
		id: 2,
		longitude: 21.1125,
		latitude: 52.2285,
		name: "Rocky",
		type: "Dog",
		breed: "German Shepherd",
		info: "Loyal and protective",
		imgPath: "",
	},
	{
		id: 3,
		longitude: 21.5142,
		latitude: 52.2308,
		name: "Charlie",
		type: "Dog",
		breed: "Beagle",
		info: "Curious and friendly",
		imgPath: "",
	},
	{
		id: 4,
		longitude: 21.017,
		latitude: 51.228,
		name: "Max",
		type: "Dog",
		breed: "Labrador Retriever",
		info: "Energetic and friendly",
		imgPath: "",
	},
	{
		id: 5,
		longitude: 21.0185,
		latitude: 52.2315,
		name: "Daisy",
		type: "Dog",
		breed: "Dachshund",
		info: "Clever and playful",
		imgPath: "",
	},
	{
		id: 6,
		longitude: 21.02,
		latitude: 52.129,
		name: "Bailey",
		type: "Dog",
		breed: "Boxer",
		info: "Energetic and affectionate",
		imgPath: "",
	},
	{
		id: 7,
		longitude: 21.122,
		latitude: 52.23,
		name: "Luna",
		type: "Dog",
		breed: "Siberian Husky",
		info: "Gentle and outgoing",
		imgPath: "",
	},
	{
		id: 8,
		longitude: 21.024,
		latitude: 52.2285,
		name: "Cooper",
		type: "Dog",
		breed: "Cavalier King Charles Spaniel",
		info: "Affectionate and friendly",
		imgPath: "",
	},
	{
		id: 9,
		longitude: 21.9,
		latitude: 52.231,
		name: "Zoe",
		type: "Dog",
		breed: "Shih Tzu",
		info: "Sweet and gentle",
		imgPath: "",
	},
	{
		id: 10,
		longitude: 21.028,
		latitude: 52.229,
		name: "Teddy",
		type: "Dog",
		breed: "Poodle",
		info: "Intelligent and hypoallergenic",
		imgPath: "",
	},
];
