const animal = {
  id: "",
  longitude: "",
  latitude: "",
  name: "",
  type: "",
  breed: "",
  info: "",
  imgPath: "",
};

export let animalData = [
  {
    id: 1,
    longitude: 21.01,
    latitude: 52.231,
    name: "Buddy",
    type: "Pies",
    breed: "Golden Retriever",
    info: "Przyjazny i zabawowy",
    imgPath: "",
  },
  {
    id: 2,
    longitude: 21.1125,
    latitude: 52.2285,
    name: "Rocky",
    type: "Pies",
    breed: "Owczarek Niemiecki",
    info: "Lojalny i ochronny",
    imgPath: "",
  },
  {
    id: 3,
    longitude: 21.5142,
    latitude: 52.2308,
    name: "Charlie",
    type: "Pies",
    breed: "Beagle",
    info: "Ciekawski i przyjazny",
    imgPath: "",
  },
  {
    id: 4,
    longitude: 21.017,
    latitude: 51.228,
    name: "Max",
    type: "Pies",
    breed: "Labrador Retriever",
    info: "Energetyczny i przyjazny",
    imgPath: "",
  },
  {
    id: 5,
    longitude: 21.0185,
    latitude: 52.2315,
    name: "Daisy",
    type: "Pies",
    breed: "Dachshund",
    info: "Sprytny i zabawowy",
    imgPath: "",
  },
  {
    id: 6,
    longitude: 21.02,
    latitude: 52.129,
    name: "Bailey",
    type: "Pies",
    breed: "Boxer",
    info: "Energetyczny i czuły",
    imgPath: "",
  },
  {
    id: 7,
    longitude: 21.122,
    latitude: 52.23,
    name: "Luna",
    type: "Pies",
    breed: "Siberian Husky",
    info: "Delikatny i otwarty",
    imgPath: "",
  },
  {
    id: 8,
    longitude: 21.024,
    latitude: 52.2285,
    name: "Cooper",
    type: "Pies",
    breed: "Cavalier King Charles Spaniel",
    info: "Czuły i przyjazny",
    imgPath: "",
  },
  {
    id: 9,
    longitude: 21.9,
    latitude: 52.231,
    name: "Zoe",
    type: "Pies",
    breed: "Shih Tzu",
    info: "Słodka i łagodna",
    imgPath: "",
  },
  {
    id: 10,
    longitude: 21.028,
    latitude: 52.229,
    name: "Teddy",
    type: "Pies",
    breed: "Pudel",
    info: "Inteligentny i hipoalergiczny",
    imgPath: "",
  },
];

export const shelters = [
  {
    name: "Koci Azyl - Fundacja św. Franciszka Pomóż Zwierzętom - Naszym Małym Braciom",
    profession: "Koty",
    longitude: 21.113301,
    latitude: 52.104742,
    animals: animalData,
  },
];
