const animal = {
	id: "",
	longitude: "",
	latitude: "",
	name: "",
	type: "",
	breed: "",
	info: "",
	imgPath: "",
};

// for test purposes, will be fetched in future
export const animalData = [
	{
		id: "1",
		longitude: "-73.935242",
		latitude: "40.730610",
		name: "Buddy",
		type: "Dog",
		breed: "Golden Retriever",
		info: "Friendly and playfulFriendly and playfulFriendly and playfulFriendly and playfulFriendly and playfulFriendly and playfulFriendly and playfulFriendly and playfulFriendly and playfulFriendly and playfulFriendly and playfulFriendly and playful",
		imgPath: "",
	},
	{
		id: "2",
		longitude: "-74.0060",
		latitude: "40.7128",
		name: "Rocky",
		type: "Dog",
		breed: "German Shepherd",
		info: "Loyal and protective",
		imgPath: "",
	},
	{
		id: "3",
		longitude: "-118.2437",
		latitude: "34.0522",
		name: "Charlie",
		type: "Dog",
		breed: "Beagle",
		info: "Curious and friendly",
		imgPath: "",
	},
	{
		id: "4",
		longitude: "-87.6298",
		latitude: "41.8781",
		name: "Max",
		type: "Dog",
		breed: "Labrador Retriever",
		info: "Energetic and friendly",
		imgPath: "",
	},
	{
		id: "5",
		longitude: "0.1276",
		latitude: "51.5074",
		name: "Daisy",
		type: "Dog",
		breed: "Dachshund",
		info: "Clever and playful",
		imgPath: "",
	},
	{
		id: "6",
		longitude: "2.3522",
		latitude: "48.8566",
		name: "Bailey",
		type: "Dog",
		breed: "Boxer",
		info: "Energetic and affectionate",
		imgPath: "",
	},
	{
		id: "7",
		longitude: "-77.0369",
		latitude: "38.9072",
		name: "Luna",
		type: "Dog",
		breed: "Siberian Husky",
		info: "Gentle and outgoing",
		imgPath: "",
	},
	{
		id: "8",
		longitude: "-0.1280",
		latitude: "51.5074",
		name: "Cooper",
		type: "Dog",
		breed: "Cavalier King Charles Spaniel",
		info: "Affectionate and friendly",
		imgPath: "",
	},
	{
		id: "9",
		longitude: "-118.4912",
		latitude: "34.0194",
		name: "Zoe",
		type: "Dog",
		breed: "Shih Tzu",
		info: "Sweet and gentle",
		imgPath: "",
	},
	{
		id: "10",
		longitude: "151.2093",
		latitude: "-33.8688",
		name: "Teddy",
		type: "Dog",
		breed: "Poodle",
		info: "Intelligent and hypoallergenic",
		imgPath: "",
	},
];
